// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StanceNation_1.Data;

#nullable disable

namespace StanceNation_1.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20231114131531_localCreate")]
    partial class localCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StanceNation_1.Models.EventsModel", b =>
                {
                    b.Property<string>("eventName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("eventDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("eventImage")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("eventLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eventPrice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eventPrice2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eventTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("eventName");

                    b.ToTable("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
